import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PDFProvider } from "@/context/PDFContext";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-5xl mx-auto min-h-screen border-l border-r sm:border-0 md:border-l md:border-r">
          <Navbar />
          <PDFProvider>{children}</PDFProvider>
          <div className="text-center py-11 border-t border-dashed">
            <p>
              Built By{" "}
              <span className="font-semibold underline">Suvaranjan</span>
            </p>
          </div>
        </main>
      </body>
    </html>
  );
}
